# Create a virtual machine image using Azure Image Builder.

- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: profile
      prompt: Enter the profile name
      private: no
  tasks:
    - name: Create random template name
      set_fact:
        template_name: "Build-{{ 999 | random(start=100) }}-{{ 999 | random(start=100) }}"

    - name: Show template name
      debug:
        msg: "The template name is: {{ template_name }}"

    - name: Create the image builder template
      command: az deployment group create --subscription {{ subscription_id }} --resource-group {{ resource_group }} -p templateName={{ template_name }} -f profiles/{{ profile | quote }}.bicep

    - name: Run the image builder template (may take up to an hour)
      command: az image builder run --subscription {{ subscription_id }} --resource-group {{ resource_group }} --name {{ template_name }}

    - name: Delete the image builder template
      command: az image builder delete --subscription {{ subscription_id }} --resource-group {{ resource_group }} --name {{ template_name }}
