# List the image versions built for the given profile.

- hosts: localhost
  gather_facts: no
  vars_prompt:
    - name: profile
      prompt: Enter the profile name
      private: no
  tasks:
    - name: List image versions
      command: az sig image-version list
        --subscription {{ subscription_id }}
        --resource-group {{ resource_group }}
        --gallery-name {{ gallery }}
        --gallery-image-definition {{ profile }}
        --output table
      register: image_versions

    - name: Show image versions
      debug:
        var: image_versions.stdout_lines
